name: build

env:
  CONAN_REMOTE: "${{ secrets.CONAN_REMOTE }}"
  CONAN_USER: "${{ secrets.CONAN_USER }}"
  CONAN_PASSWORD: "${{ secrets.CONAN_PASSWORD }}"


on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: build-all
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os:
          - windows-latest
          - macos-10.13
          - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Checkout profiles
        uses: actions/checkout@v2
        with:
          repository: conan-burrito/profiles
          path: profiles
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install conan conan_package_tools
          conan config install ${{ github.workspace }}/profiles/settings.yml
          conan remote add -i 0 conan_burrito "${{ env.CONAN_REMOTE }}"
          conan user -r conan_burrito "${{ env.CONAN_USER }}" -p "${{ env.CONAN_PASSWORD }}"

      - name: Build native
        run:  |
          python .ci/build.py
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: serial-plotter
          path: ${{ github.workspace }}/_build/serial-plotter-*.zip